packages:
  - ember-engines-router-service
  - test-app

onlyBuiltDependencies:
  - core-js

overrides:
  ember-cli-htmlbars: ^7.0.1

patchedDependencies:
  ember-asset-loader@1.0.0: patches/ember-asset-loader@1.0.0.patch
